server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: haigou-config
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/SeanJian0918/haigou.git
          username: SeanJian0918
          password: jianzhihai0918